export const ActionTypes = {
  FETCH_TRENDALL: "FETCH_TRENDALL",
  FETCH_SERIES: "FETCH_SERIES",
  FETCH_MOVIES: "FETCH_MOVIES",
  SELECTED_MOVIE: "SELECTED_MOVIE",
  // FETCH_MOVIES_BY_NAME: "FETCH_MOVIES_BY_NAME",

  Clear_SELECTED_MOVIE: "REMOVE_SELECTED_MOVIE",
};
